services:
  workbookserver:
    container_name: workbook-server
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017/mongodb?authSource=admin
    depends_on:
      - mongodb

  mongodb:
    container_name: workbook_db
    user: "999:999"
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - /Users/minsung/IdeaProjects/workbook/data:/data/db
    restart: always

volumes:
  mongodb:
